import { useState } from "react";
import "./App.css";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

export default function App() {
  const [file, setFile] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [labs, setLabs] = useState([]);
  const [insights, setInsights] = useState("");
  const [error, setError] = useState("");

  const handleFileChange = (e) => {
    setFile(e.target.files[0] || null);
    setLabs([]);
    setInsights("");
    setError("");
  };

  const handleAnalyze = async () => {
    if (!file) {
      alert("Please select a PDF file first.");
      return;
    }

    setIsLoading(true);
    setError("");
    setLabs([]);
    setInsights("");

    try {
      const formData = new FormData();
      formData.append("file", file);

      const res = await fetch(`${API_BASE_URL}/analyze-report`, {
        method: "POST",
        body: formData,
      });

      if (!res.ok) {
        const text = await res.text();
        throw new Error(text || "Request failed");
      }

      const data = await res.json();
      setLabs(data.labs || []);
      setInsights(data.insights || "");
    } catch (err) {
      console.error(err);
      setError("Something went wrong while analyzing the report. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="container">
      <header className="header">
        <h1>🩺 Vital Insights</h1>
        <p className="subtitle">
          Upload your blood test report (PDF) to see structured lab values and AI-generated insights.
        </p>
      </header>

      {/* Upload Section */}
      <div className="upload-section">
        <input
          type="file"
          accept="application/pdf"
          onChange={handleFileChange}
          className="file-input"
          id="file-upload"
        />
        <label htmlFor="file-upload" className="file-label">
          {file ? file.name : "Choose PDF file"}
        </label>
        <button
          onClick={handleAnalyze}
          className="analyze-btn"
          disabled={isLoading || !file}
        >
          {isLoading ? "Analyzing..." : "Analyze Report"}
        </button>

        {error && (
          <div className="error-message">
            ⚠️ {error}
          </div>
        )}
      </div>

      {isLoading && (
        <div className="loading">
          <div className="spinner"></div>
          <p>Processing your report and generating insights…</p>
        </div>
      )}

      {/* Results Section */}
      {!isLoading && labs.length > 0 && (
        <div className="results">
          {/* Lab Results Table */}
          <section className="results-section">
            <h2>📊 Lab Results</h2>
            <div className="table-wrapper">
              <table className="results-table">
                <thead>
                  <tr>
                    <th>Test Name</th>
                    <th>Category</th>
                    <th>Value</th>
                    <th>Reference Range</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {labs.map((lab, idx) => (
                    <tr key={idx}>
                      <td className="test-name">
                        {lab.test_name}
                        {lab.test_code && (
                          <span className="test-code"> ({lab.test_code})</span>
                        )}
                      </td>
                      <td className="category">{lab.category || "—"}</td>
                      <td className="value">
                        {lab.value} <span className="unit">{lab.unit}</span>
                      </td>
                      <td className="range">
                        {lab.ref_low} – {lab.ref_high} {lab.unit}
                      </td>
                      <td>
                        <StatusPill flag={lab.flag} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* AI Insights */}
          <section className="results-section">
            <h2>🤖 AI Insights</h2>
            <div className="insights-box">
              {insights}
            </div>
            <p className="disclaimer">
              <strong>Disclaimer:</strong> These insights are generated by AI for educational purposes only 
              and are not medical advice. Always consult a healthcare professional about your results.
            </p>
          </section>
        </div>
      )}
    </div>
  );
}

function StatusPill({ flag }) {
  const normalized = (flag || "").toUpperCase();
  let className = "status-pill normal";
  let label = "Normal";

  if (normalized === "HIGH") {
    className = "status-pill high";
    label = "High";
  } else if (normalized === "LOW") {
    className = "status-pill low";
    label = "Low";
  } else if (normalized === "CRITICAL") {
    className = "status-pill critical";
    label = "Critical";
  }

  return <span className={className}>{label}</span>;
}